import { Notice } from 'obsidian';
import type { FolderGraph, MapNode, SavedNodePosition } from '../core/graph';
import { folderDisplayName } from '../core/paths';

interface ExcalidrawElementLike {
	link?: string;
	strokeColor?: string;
	backgroundColor?: string;
}

interface ExcalidrawAutomateLike {
	reset(): void;
	addEllipse(x: number, y: number, width: number, height: number): string;
	addText(
		x: number,
		y: number,
		text: string,
		formatting?: { width?: number; textAlign?: 'left' | 'center' | 'right'; box?: boolean | 'ellipse' },
	): string;
	addArrow(
		points: [number, number][],
		formatting?: { startObjectId?: string; endObjectId?: string },
	): string;
	getElement(id: string): ExcalidrawElementLike | undefined;
	isExcalidrawFile?(file: import('obsidian').TFile): boolean;
	create(params?: {
		filename?: string;
		foldername?: string;
		onNewPane?: boolean;
		silent?: boolean;
		plaintext?: string;
	}): Promise<string>;
}

declare global {
	interface Window {
		ExcalidrawAutomate?: ExcalidrawAutomateLike;
	}
}

function drawingName(prefix: string): string {
	const timestamp = new Date().toISOString().replaceAll(':', '-').replace('T', ' ').slice(0, 19);
	return `${prefix} ${timestamp}`;
}

export class ExcalidrawIntegration {
	get available(): boolean {
		return Boolean(window.ExcalidrawAutomate);
	}

	isDrawing(file: import('obsidian').TFile): boolean {
		return window.ExcalidrawAutomate?.isExcalidrawFile?.(file) ?? file.path.endsWith('.excalidraw.md');
	}

	async createBlank(folderPath: string): Promise<void> {
		const ea = this.requireApi();
		if (!ea) return;
		ea.reset();
		await ea.create({
			filename: drawingName('Knowledge canvas'),
			foldername: folderPath === '/' ? undefined : folderPath,
			onNewPane: true,
			plaintext: 'Created by Knowledge Map. This is a standard Excalidraw drawing.',
		});
	}

	async createFromGraph(
		folderPath: string,
		graph: FolderGraph,
		positions: Record<string, SavedNodePosition>,
	): Promise<void> {
		const ea = this.requireApi();
		if (!ea) return;
		ea.reset();
		const elementIds = new Map<string, string>();

		for (const node of graph.nodes) {
			const point = positions[node.id];
			if (!point) continue;
			const isFolder = node.kind === 'folder' || node.kind === 'current-folder';
			const size = isFolder ? 112 : 84;
			const x = point.x * 1.35 - size / 2;
			const y = point.y * 1.35 - size / 2;
			const ellipseId = ea.addEllipse(x, y, size, size);
			const ellipse = ea.getElement(ellipseId);
			if (ellipse) {
				ellipse.strokeColor = isFolder ? '#d97706' : '#4f83cc';
				ellipse.backgroundColor = isFolder ? '#fef3c7' : '#dbeafe';
				ellipse.link = this.nodeLink(node);
			}
			ea.addText(x, y + size / 2 - 10, node.label, {
				width: size,
				textAlign: 'center',
			});
			elementIds.set(node.id, ellipseId);
		}

		for (const edge of graph.edges) {
			const from = positions[edge.from];
			const to = positions[edge.to];
			const fromId = elementIds.get(edge.from);
			const toId = elementIds.get(edge.to);
			if (!from || !to || !fromId || !toId) continue;
			ea.addArrow(
				[[from.x * 1.35, from.y * 1.35], [to.x * 1.35, to.y * 1.35]],
				{ startObjectId: fromId, endObjectId: toId },
			);
		}

		await ea.create({
			filename: drawingName(`${folderDisplayName(folderPath)} map`),
			foldername: folderPath === '/' ? undefined : folderPath,
			onNewPane: true,
			plaintext: 'Generated by Knowledge Map. Nodes are links to real vault files and folders.',
		});
	}

	private nodeLink(node: MapNode): string {
		if (node.kind === 'folder' || node.kind === 'current-folder') {
			return `obsidian://open?path=${encodeURIComponent(node.path)}`;
		}
		return `[[${node.path}]]`;
	}

	private requireApi(): ExcalidrawAutomateLike | null {
		const api = window.ExcalidrawAutomate;
		if (api) return api;
		new Notice('Install and enable the Excalidraw plugin to use freeform canvases.');
		return null;
	}
}
